"""
Persistence for scans and complaints.

Two stores behind one contract, chosen by whether `DATABASE_URL` is set.

  **PostgreSQL** — where a deployment keeps its data. The host this runs on
  gives a free instance a temporary disk: it is wiped on every deploy and on
  every restart, which took the scan history with it each time the service was
  updated. History that disappears when the product is improved is not history,
  so the store moved somewhere that outlives the container.

  **SQLite** — the fallback, and what a checkout runs on. No server, no
  connection string, a file beside the application. Good for development and
  for anyone reading this repository without credentials.

The two speak nearly the same SQL. The differences that matter — placeholder
syntax, the type a photograph is stored in, how a table is inspected — are
handled here, so nothing above this file knows which store it is talking to.
"""

import json
import os
import re
import sqlite3
import threading
from datetime import datetime, timezone
from typing import Any, Optional

DB_PATH = os.getenv("DATABASE_PATH", "niriksha.db")

# The connection string of a hosted PostgreSQL database. Set, everything below
# uses it; unset, the file store stands in. It carries a password, so it comes
# from the environment and is never committed.
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

USE_POSTGRES = bool(DATABASE_URL)

# SQLite allows one writer at a time; serialising writes in-process keeps
# concurrent uploads from tripping over each other. Harmless on PostgreSQL,
# which does its own locking, and kept so both paths behave identically.
_lock = threading.Lock()

# Dialect differences, in one place.
_BLOB = "BYTEA" if USE_POSTGRES else "BLOB"
_AUTO_ID = (
    "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    if USE_POSTGRES
    else "INTEGER PRIMARY KEY AUTOINCREMENT"
)


def _integrity_errors() -> tuple:
    """
    The exception each driver raises when a unique index refuses a row.

    Caught by type rather than by message: the idempotent write below depends
    on telling "this event is already recorded" apart from a real failure, and
    a string match would break the first time a driver reworded itself.
    """
    if USE_POSTGRES:
        import psycopg

        return (psycopg.errors.UniqueViolation, psycopg.errors.IntegrityError)

    return (sqlite3.IntegrityError,)


# Comparing a column against a value that may be NULL, where NULL should match
# NULL. SQLite spells this `IS`; PostgreSQL reserves `IS` for NULL, TRUE and
# FALSE literals and rejects a parameter after it, which is why every
# owner-scoped query returned a syntax error the moment the store moved.
_OWNED_BY = (
    "user_id IS NOT DISTINCT FROM ?" if USE_POSTGRES else "user_id IS ?"
)


def _translate(sql: str) -> str:
    """
    Rewrites SQLite's `?` placeholders as the `%s` psycopg expects.

    Only outside string literals: a `?` inside quoted text is data, not a
    placeholder, and rewriting it would corrupt the query.
    """
    out = []
    quote = None

    for character in sql:
        if quote:
            if character == quote:
                quote = None
            out.append(character)
        elif character in ("'", '"'):
            quote = character
            out.append(character)
        elif character == "?":
            out.append("%s")
        else:
            out.append(character)

    return "".join(out)


class _PostgresConnection:
    """
    A psycopg connection that answers to the sqlite3 calls this module makes.

    The alternative was rewriting every query in this file twice. This keeps
    one set of SQL and confines the difference to placeholder syntax and row
    access, both of which are mechanical.
    """

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql: str, params: tuple = ()):
        cursor = self._connection.cursor()
        cursor.execute(_translate(sql), params)
        return cursor

    def executescript(self, script: str) -> None:
        with self._connection.cursor() as cursor:
            for statement in script.split(";"):
                if statement.strip():
                    cursor.execute(statement)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        # Same contract as sqlite3's context manager: commit on success, roll
        # back on the way out of an exception.
        if exc_type is None:
            self._connection.commit()
        else:
            self._connection.rollback()

        self._connection.close()
        return False


# Set when PostgreSQL was configured but could not be reached, so the store
# fell back to the local file. Reported by /health/processing: a deployment
# quietly writing to a disk that is wiped on the next deploy is the failure
# this module exists to prevent, and it must not be invisible.
POSTGRES_UNAVAILABLE: Optional[str] = None


_IntegrityError = _integrity_errors()


def _connect():
    if USE_POSTGRES:
        import psycopg
        from psycopg.rows import dict_row

        # Prepared statements are turned off deliberately. Supabase is reached
        # through a connection pooler, and in transaction mode a pooler hands
        # each statement to whichever backend is free — a statement prepared
        # on one connection is not there on the next, and the query fails with
        # a message that points nowhere near the cause. Off, every statement
        # is self-contained and any pooler mode works.
        return _PostgresConnection(
            psycopg.connect(DATABASE_URL, row_factory=dict_row, prepare_threshold=None)
        )

    connection = sqlite3.connect(DB_PATH, timeout=10)
    connection.row_factory = sqlite3.Row
    return connection


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _verify_postgres() -> None:
    """
    Opens one connection before anything depends on it.

    A bad password or an unreachable host would otherwise surface as a failed
    startup, and a backend that will not start is worse than one storing to
    the wrong place. This turns it into a degraded mode that says so.
    """
    global USE_POSTGRES, POSTGRES_UNAVAILABLE, _BLOB, _AUTO_ID, _IntegrityError

    if not USE_POSTGRES:
        return

    try:
        with _connect() as db:
            db.execute("SELECT 1").fetchone()

            # Not just "can we connect", but "does the SQL this module writes
            # actually run here". The two stores differ in ways a connection
            # test cannot see: SQLite accepts `IS ?` for a null-safe
            # comparison and PostgreSQL rejects it, so every owner-scoped
            # query failed on the store while passing every test against the
            # file. A representative one runs here, at startup, where the
            # failure is loud and nobody is waiting on it.
            db.execute(
                f"SELECT 1 FROM (SELECT NULL AS user_id) AS probe WHERE {_OWNED_BY}",
                (None,),
            ).fetchone()

    except Exception as error:
        POSTGRES_UNAVAILABLE = str(error)

        print(
            "DATABASE_URL is set but PostgreSQL could not be reached, so this "
            "deployment is falling back to the local file. Scans recorded now "
            "will be lost on the next deploy. Reason:",
            POSTGRES_UNAVAILABLE,
        )

        USE_POSTGRES = False
        _BLOB = "BLOB"
        _AUTO_ID = "INTEGER PRIMARY KEY AUTOINCREMENT"
        _IntegrityError = (sqlite3.IntegrityError,)


def store_status() -> dict[str, Any]:
    """Which store is in use, and whether it is the one that was asked for."""
    return {
        "store": "postgres" if USE_POSTGRES else "sqlite",
        "durable": USE_POSTGRES,
        "fallback_reason": POSTGRES_UNAVAILABLE,
    }


def init_db() -> None:
    """Creates the schema. Safe to call on every start."""
    _verify_postgres()

    with _lock, _connect() as db:
        db.executescript(
            f"""
            CREATE TABLE IF NOT EXISTS scans (
                id            TEXT PRIMARY KEY,
                created_at    TEXT NOT NULL,
                filename      TEXT,
                product_name  TEXT,
                net_quantity  TEXT,
                scan_status   TEXT NOT NULL,
                status        TEXT,
                score         INTEGER,
                result_json   TEXT NOT NULL,
                -- The Supabase user whose scan this is, taken from the `sub`
                -- claim of a verified access token. Null for rows written
                -- before scans had owners, and for an unconfigured local run.
                user_id       TEXT,
                -- The client's identifier for one scan action. Two requests
                -- carrying the same one are the same event -- a retry, a
                -- double submit -- and must not become two rows.
                scan_event_id TEXT,
                -- The photograph this assessment was made from, kept with the
                -- scan rather than in a directory beside it. Every finding
                -- below is a claim about this picture, and a report opened
                -- later has nothing to show without it.
                image_bytes   {_BLOB},
                image_mime    TEXT,
                -- What was assessed: a photographed package, or the text of
                -- an online listing. They are held together because they are
                -- the same assessment against the same Rules, and a history
                -- that showed only one of them would be a partial record.
                source_kind   TEXT
            );

            CREATE TABLE IF NOT EXISTS complaints (
                id             TEXT PRIMARY KEY,
                scan_id        TEXT,
                product        TEXT,
                violation_type TEXT NOT NULL,
                description    TEXT NOT NULL,
                location       TEXT,
                contact        TEXT,
                status         TEXT NOT NULL,
                created_at     TEXT NOT NULL,
                updated_at     TEXT NOT NULL
            );

            -- Append-only: the audit trail behind every status change.
            CREATE TABLE IF NOT EXISTS complaint_events (
                id           {_AUTO_ID},
                complaint_id TEXT NOT NULL,
                status       TEXT NOT NULL,
                note         TEXT,
                created_at   TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_scans_created ON scans (created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_complaints_created ON complaints (created_at DESC);
            """
        )

        # A database created before scans had owners already has the table, so
        # the CREATE above left it untouched and the new columns have to be
        # added on their own.
        #
        # Existing rows keep a null owner. Nobody can say now whose they were,
        # and assigning them to whoever asks first would put one person's
        # inspections in another person's history -- the failure this column
        # exists to prevent.
        # Which columns the table already has. PRAGMA is SQLite's; PostgreSQL
        # answers the same question from its catalogue.
        if USE_POSTGRES:
            columns = {
                row["column_name"]
                for row in db.execute(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_name = 'scans'"
                ).fetchall()
            }
        else:
            columns = {
                row["name"]
                for row in db.execute("PRAGMA table_info(scans)").fetchall()
            }

        if "user_id" not in columns:
            db.execute("ALTER TABLE scans ADD COLUMN user_id TEXT")

        if "scan_event_id" not in columns:
            db.execute("ALTER TABLE scans ADD COLUMN scan_event_id TEXT")

        if "image_bytes" not in columns:
            db.execute(f"ALTER TABLE scans ADD COLUMN image_bytes {_BLOB}")

        if "image_mime" not in columns:
            db.execute("ALTER TABLE scans ADD COLUMN image_mime TEXT")

        if "source_kind" not in columns:
            db.execute("ALTER TABLE scans ADD COLUMN source_kind TEXT")

        # Indexed here, not in the script above: on an older database neither
        # column exists until the lines above add it.
        db.execute(
            "CREATE INDEX IF NOT EXISTS idx_scans_user "
            "ON scans (user_id, created_at DESC)"
        )

        # The rule that makes recording a scan idempotent. Partial, because
        # every row written before this existed has no event id and they must
        # not all collide with each other.
        db.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_scans_event "
            "ON scans (scan_event_id) WHERE scan_event_id IS NOT NULL"
        )


def _next_reference(table: str, prefix: str) -> str:
    """
    Sequential, human-quotable reference: NIR-2026-00001.

    Taken from the highest number already issued this year rather than from a
    row count. A count repeats itself the moment anything is deleted, and the
    reference is the primary key — a repeat is a lost scan, not a cosmetic
    problem. Concurrent writers can still pick the same number; the primary
    key refuses the second, and the caller retries.
    """
    year = datetime.now(timezone.utc).year
    pattern = f"{prefix}-{year}-%"

    with _connect() as db:
        row = db.execute(
            f"SELECT MAX(id) AS highest FROM {table} WHERE id LIKE ?",
            (pattern,),
        ).fetchone()

    highest = (row or {})["highest"] if row else None

    try:
        # The last five characters are the sequence; anything else is not one
        # of ours and is ignored rather than crashing the scan.
        used = int(str(highest).rsplit("-", 1)[1]) if highest else 0
    except (IndexError, ValueError):
        used = 0

    return f"{prefix}-{year}-{used + 1:05d}"


# ============================================================
# SCANS
# ============================================================

def record_scan(
    result: dict[str, Any],
    user_id: Optional[str] = None,
    event_id: Optional[str] = None,
    image: Optional[tuple[bytes, str]] = None,
    source_kind: str = "image",
) -> str:
    """
    Stores one completed scan and returns its reference.

    The whole response is kept as JSON so a past scan can be re-opened exactly
    as it was assessed, rather than reconstructed from summary columns.

    One scan action produces one row. The client names the action in
    `event_id`, and a second request carrying an id already on file returns
    the reference that was issued the first time instead of minting another.
    That covers a retried request, a double submit, and a repeat of an
    identical image answered from the cache -- all of which used to leave the
    same product in the history several times over.

    Scanning the same packet again deliberately is a different action with a
    different id, and gets a row and a reference of its own. The identity here
    is the event, never the product.
    """
    product = result.get("product") or {}
    compliance = result.get("compliance") or {}

    with _lock, _connect() as db:

        if event_id:
            existing = db.execute(
                "SELECT id FROM scans WHERE scan_event_id = ?",
                (event_id,),
            ).fetchone()

            if existing is not None:
                return existing["id"]

        scan_id = _next_reference("scans", "NIR")

        try:
            db.execute(
                """
                INSERT INTO scans (id, created_at, filename, product_name, net_quantity,
                                   scan_status, status, score, result_json,
                                   user_id, scan_event_id, image_bytes, image_mime,
                                   source_kind)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    scan_id,
                    _now(),
                    result.get("filename"),
                    product.get("product_name"),
                    product.get("net_quantity"),
                    result.get("scan_status", "UNKNOWN"),
                    compliance.get("status"),
                    compliance.get("score"),
                    json.dumps(result),
                    user_id,
                    event_id,
                    image[0] if image else None,
                    image[1] if image else None,
                    source_kind,
                ),
            )

        except _IntegrityError:
            # Two requests for the same event arrived close enough together
            # that both passed the check above. The unique index settles it;
            # the loser reports the reference the winner was given.
            existing = db.execute(
                "SELECT id FROM scans WHERE scan_event_id = ?",
                (event_id,),
            ).fetchone()

            if existing is not None:
                return existing["id"]

            # Not the event index, then: two scans picked the same reference
            # in the same moment. The number is the primary key, so one of
            # them has to take the next one rather than fail.
            for _ in range(5):
                scan_id = _next_reference("scans", "NIR")

                try:
                    db.execute(
                        """
                        INSERT INTO scans (id, created_at, filename, product_name, net_quantity,
                                           scan_status, status, score, result_json,
                                           user_id, scan_event_id, image_bytes, image_mime)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            scan_id,
                            _now(),
                            result.get("filename"),
                            product.get("product_name"),
                            product.get("net_quantity"),
                            result.get("scan_status", "UNKNOWN"),
                            compliance.get("status"),
                            compliance.get("score"),
                            json.dumps(result),
                            user_id,
                            event_id,
                            image[0] if image else None,
                            image[1] if image else None,
                        ),
                    )
                    break

                except _IntegrityError:
                    continue

            else:
                # Five collisions in a row is not contention any more.
                raise

    return scan_id


def list_scans(
    limit: int = 100,
    user_id: Optional[str] = None,
) -> list[dict[str, Any]]:
    """
    One user's scans, newest first.

    The owner is always part of the query. A null owner is a scope of its own
    -- the rows recorded without a signed-in user -- and not a wildcard, so
    there is no argument to this function that returns everybody's history.
    """
    with _connect() as db:
        rows = db.execute(
            f"""
            SELECT id, created_at, filename, product_name, net_quantity,
                   scan_status, status, score, source_kind
            FROM scans
            WHERE {_OWNED_BY}
            ORDER BY created_at DESC LIMIT ?
            """,
            (user_id, limit),
        ).fetchall()
    return [dict(row) for row in rows]


def get_scan(
    scan_id: str,
    user_id: Optional[str] = None,
) -> Optional[dict[str, Any]]:
    """
    One stored scan, if it belongs to this user.

    Scoped for the same reason the listing is: a reference is short and
    guessable, and without the owner in the query anyone could read anyone
    else's inspection by typing a number.
    """
    with _connect() as db:
        row = db.execute(
            f"SELECT result_json FROM scans WHERE id = ? AND {_OWNED_BY}",
            (scan_id, user_id),
        ).fetchone()
    return json.loads(row["result_json"]) if row else None


def get_scan_image(
    scan_id: str,
    user_id: Optional[str] = None,
) -> Optional[tuple[bytes, str]]:
    """
    The photograph belonging to one scan, if it belongs to this user.

    Scoped exactly as the assessment itself is. A picture of somebody's
    shopping is theirs, and a reference number is short enough to guess.
    """
    with _connect() as db:
        row = db.execute(
            f"SELECT image_bytes, image_mime FROM scans WHERE id = ? AND {_OWNED_BY}",
            (scan_id, user_id),
        ).fetchone()

    if row is None or row["image_bytes"] is None:
        return None

    return bytes(row["image_bytes"]), row["image_mime"] or "image/jpeg"


def scan_stats(user_id: Optional[str] = None) -> dict[str, int]:
    """
    Counts by outcome, for the dashboard and history headers.

    Scoped exactly as the listing is: a total that counts rows the page does
    not show is a page contradicting itself.
    """
    with _connect() as db:
        rows = db.execute(
            "SELECT status, scan_status, COUNT(*) AS n FROM scans "
            f"WHERE {_OWNED_BY} GROUP BY status, scan_status",
            (user_id,),
        ).fetchall()
        complaints = db.execute("SELECT COUNT(*) AS n FROM complaints").fetchone()["n"]

    stats = {
        "inspected": 0,
        "compliant": 0,
        "nonCompliant": 0,
        "needsReview": 0,
        "retakeRequired": 0,
        "complaints": complaints,
    }

    for row in rows:
        stats["inspected"] += row["n"]
        if row["scan_status"] == "RETAKE_REQUIRED":
            stats["retakeRequired"] += row["n"]
        elif row["status"] == "COMPLIANT":
            stats["compliant"] += row["n"]
        elif row["status"] == "NON_COMPLIANT":
            stats["nonCompliant"] += row["n"]
        elif row["status"] == "PARTIALLY_COMPLIANT":
            stats["needsReview"] += row["n"]

    return stats


# ============================================================
# COMPLAINTS
# ============================================================

VALID_STATUSES = ["submitted", "under_review", "verified", "action_taken", "rejected"]

# A complaint cannot jump straight to a conclusion: each move is recorded.
TRANSITIONS: dict[str, list[str]] = {
    "submitted": ["under_review", "rejected"],
    "under_review": ["verified", "rejected"],
    "verified": ["action_taken", "rejected"],
    "action_taken": [],
    "rejected": ["under_review"],
}


def create_complaint(
    scan_id: Optional[str],
    product: Optional[str],
    violation_type: str,
    description: str,
    location: Optional[str],
    contact: Optional[str],
) -> dict[str, Any]:
    complaint_id = _next_reference("complaints", "NIR-CMP")
    now = _now()

    with _lock, _connect() as db:
        db.execute(
            """
            INSERT INTO complaints (id, scan_id, product, violation_type, description,
                                    location, contact, status, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, 'submitted', ?, ?)
            """,
            (complaint_id, scan_id, product, violation_type, description, location, contact, now, now),
        )
        db.execute(
            "INSERT INTO complaint_events (complaint_id, status, note, created_at) VALUES (?, ?, ?, ?)",
            (
                complaint_id,
                "submitted",
                "Complaint recorded in the NIRIKSHA system with the assessment findings attached.",
                now,
            ),
        )

    return get_complaint(complaint_id)  # type: ignore[return-value]


def get_complaint(complaint_id: str) -> Optional[dict[str, Any]]:
    with _connect() as db:
        row = db.execute("SELECT * FROM complaints WHERE id = ?", (complaint_id,)).fetchone()
        if not row:
            return None
        events = db.execute(
            "SELECT status, note, created_at FROM complaint_events "
            "WHERE complaint_id = ? ORDER BY id",
            (complaint_id,),
        ).fetchall()

    complaint = dict(row)
    complaint["timeline"] = [dict(event) for event in events]
    return complaint


def list_complaints(limit: int = 200) -> list[dict[str, Any]]:
    with _connect() as db:
        rows = db.execute(
            "SELECT id FROM complaints ORDER BY created_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return [complaint for row in rows if (complaint := get_complaint(row["id"]))]


class TransitionError(ValueError):
    """Raised when a status change is not allowed from the current state."""


def update_complaint_status(complaint_id: str, status: str, note: Optional[str]) -> dict[str, Any]:
    complaint = get_complaint(complaint_id)
    if complaint is None:
        raise LookupError(f"No complaint with reference {complaint_id}.")

    current = complaint["status"]
    if status not in VALID_STATUSES:
        raise TransitionError(f"'{status}' is not a valid complaint status.")
    if status not in TRANSITIONS[current]:
        raise TransitionError(f"A complaint cannot move from '{current}' to '{status}'.")

    now = _now()
    with _lock, _connect() as db:
        db.execute(
            "UPDATE complaints SET status = ?, updated_at = ? WHERE id = ?",
            (status, now, complaint_id),
        )
        db.execute(
            "INSERT INTO complaint_events (complaint_id, status, note, created_at) VALUES (?, ?, ?, ?)",
            (complaint_id, status, note, now),
        )

    return get_complaint(complaint_id)  # type: ignore[return-value]
